# Generated by Django 6.0.3 on 2026-07-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, default='+1 415 555-0100', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Staff Member', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Remote', 'Remote')], default='Active', max_length=20),
        ),
    ]
